### ISSUE TITLE
How do I  install pfnncharacter.

### ISSUE THREAD

**Issue by whenflyfish** [MariaPriisalu/spl#1]
Sorry to bother.
git clone --recursive https://github.com/pybind/cmake_example.git
pip install ./pfnncharacter
I can't find pfnncharacter.And I'm trying to install by setup.py,but there are no CMakeLists.txt.

**Comment by MariaPriisalu** [comment]
Hi,

Thank you for notifying me. I have now updated the .gitignore such that
.txt files are now not ignored.
Sorry for this. I would recommend that you pull all of the changes of my
last commit as a number .txt files were ignored previously.

Best,
Maria Priisalu

**Comment by MariaPriisalu** [comment]
Hi again,

Just realized that I replied too fast. I have also edited the README.
Just run pip install ./ when in the folder spl/commonUtils/PFNNBaseCode.
You might have to adjust the CMakeList.txt

Best regards,
Maria Priisalu

**Comment by whenflyfish** [comment]
Thank you very much.
